name: ready-for-sprint-06
description: Ambiente equivalente ao final da Sprint 5
stacks:
  "01-web-edge": true
  "02-identity": false
  "03-marketplace-api": false
  "04-database": false
  "05-container-platform": false
  "06-gitops": false
