name: ready-for-sprint-04
description: Ambiente equivalente ao final da Sprint 3
stacks:
  "01-web-edge": false
  "02-identity": false
  "03-marketplace-api": false
  "04-database": false
  "05-container-platform": false
  "06-gitops": false
