name: ready-for-sprint-07
description: Ambiente equivalente ao final da Sprint 6
stacks:
  "01-web-edge": true
  "02-identity": true
  "03-marketplace-api": true
  "04-database": false
  "05-container-platform": false
  "06-gitops": false
